---
# Ansible playbook for the Windows 10 client
# Run the playbook using ` ansible-playbook client10_playbook.yml -i hosts `

- hosts: client
  gather_facts: true
  
  roles:
    - configure_win10_client
    - win_disable_uac
    - win10_caldera

